sports_app/sports_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('start.urls')),
    path('projects/', include('projects.urls')),
    path('users/', include('users.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sports_app/start/urls.py
# start/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),  # Маршрут для главной страницы
]

sports_app/users/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('', views.profiles, name='profiles'),
    path('profile/<str:pk>/', views.user_profile, name='user_profile'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('register/', views.register_user, name='register'),
    path('create_profile/', views.create_profile, name='create_profile'),
    path('offer_profile_creation/', views.offer_profile_creation, name='offer_profile_creation'),
    path('account/', views.user_account, name='account'),
    path('edit-account/', views.edit_account, name='edit-account'),
    path('create-skill/', views.create_skill, name='create-skill'),
    path('update-skill/<str:pk>/', views.update_skill, name='update-skill'),
    path('delete-skill/<str:pk>/', views.delete_skill, name='delete-skill'),
    path('like_photo/<int:photo_id>/', views.like_photo, name='like_photo'),
    path('like_video/<int:video_id>/', views.like_video, name='like_video'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('created_message/<str:pk>/', views.created_message, name='created_message'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

sports_app/projects/models.py
from django.db import models
from users.models import Profile
from django.contrib.auth.models import User
from ckeditor_uploader.fields import RichTextUploadingField


class Project(models.Model):
    owner = models.ForeignKey(Profile, on_delete=models.SET_NULL, blank=True, null=True, verbose_name='Автор')
    sections = models.ManyToManyField('Section', blank=True, verbose_name='Категории')
    title = models.CharField(max_length=200, verbose_name='Название')
    description = RichTextUploadingField(blank=True, verbose_name='Описание')
    featured_image = models.ImageField(default='default.jpg', upload_to='projects/%Y/%m/%d', verbose_name='Изображение')
    demo_link = models.CharField(max_length=200, blank=True, verbose_name='Ссылка на демонстрацию')
    source_link = models.CharField(max_length=200, blank=True, verbose_name='Ссылка на источник')
    tags = models.ManyToManyField('Tag', blank=True, verbose_name='Тег')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    likes = models.ManyToManyField(User, related_name='project_likes', blank=True, verbose_name='Лайки')

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-created']
        verbose_name = 'Статья'
        verbose_name_plural = 'статьи'


class Tag(models.Model):
    name = models.CharField(max_length=200, verbose_name='Наименование')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Дата')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Тэг'
        verbose_name_plural = 'тэги'


class Section(models.Model):
    name = models.CharField(max_length=200, verbose_name='Название раздела')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Раздел'
        verbose_name_plural = 'разделы'


class UsefulLink(models.Model):
    title = models.CharField(max_length=255, verbose_name='Наименование')
    url = models.URLField()
    icon_url = models.URLField(blank=True, null=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Сайт'
        verbose_name_plural = 'сайты'


class Comment(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE, related_name='comments')
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    profile = models.ForeignKey(Profile, on_delete=models.SET_NULL, null=True, blank=True)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.author.name} - {self.content[:50]}'

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'комментарии'

sports_app/users/models.py
from django.db import models
from django.contrib.auth.models import User


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, blank=True, verbose_name='Пользователь')
    name = models.CharField(max_length=200, blank=True, verbose_name='Имя')
    email = models.EmailField(max_length=200, blank=True, verbose_name='Эл.адрес')
    nickname = models.CharField(max_length=200, blank=True, verbose_name='Псевдоним')
    myself_short = models.CharField(max_length=200, blank=True, verbose_name='О себе коротко')
    myself = models.TextField(blank=True, verbose_name='О себе')
    photo = models.ImageField(upload_to='profiles/', default='profiles/coach.jpg', verbose_name='Фото')
    video = models.FileField(upload_to='videos/', blank=True, null=True, verbose_name='Видео')
    note = models.TextField(blank=True, null=True, verbose_name='Заметка')
    social_youtube = models.CharField(max_length=200, blank=True, verbose_name='Youtube')
    social_site = models.CharField(max_length=200, blank=True, verbose_name='Социальная сеть')
    social_website = models.CharField(max_length=200, blank=True, verbose_name='Сайт')
    document = models.FileField(upload_to='documents/', verbose_name='Документ об образовании', null=True, blank=False)
    work = models.CharField(max_length=200, blank=True, verbose_name='Место работы')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Дата')

    def __str__(self):
        return self.nickname

    class Meta:
        verbose_name = 'Профиль'
        verbose_name_plural = 'профили'


class Skill(models.Model):
    expert = models.ForeignKey(Profile, on_delete=models.CASCADE, blank=True, verbose_name='Эксперт')
    qualification = models.CharField(max_length=200, blank=True, verbose_name='Квалификация')
    info = models.TextField(blank=True, verbose_name='Описание')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Дата')

    def __str__(self):
        return self.qualification

    class Meta:
        verbose_name = 'Квалификация'
        verbose_name_plural = 'квалификации'


class Photo(models.Model):
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='photos')
    image = models.ImageField(upload_to='photos/', verbose_name='Фото')
    caption = models.TextField(blank=True, null=True, verbose_name='Подпись')
    likes = models.ManyToManyField(User, related_name='photo_likes', blank=True)
    created = models.DateTimeField(auto_now_add=True, verbose_name='Дата')

    def __str__(self):
        return f"{self.profile.nickname} - {self.created}"

    class Meta:
        verbose_name = 'Фото'
        verbose_name_plural = 'фотографии'


# class Video(models.Model):
#     profile = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='videos')
#     video = models.FileField(upload_to='videos/', verbose_name='Видео')
#     caption = models.TextField(blank=True, null=True, verbose_name='Подпись')
#     likes = models.ManyToManyField(User, related_name='video_likes', blank=True)
#     created = models.DateTimeField(auto_now_add=True, verbose_name='Дата')
#
#     def __str__(self):
#         return f"{self.profile.nickname} - {self.created}"
#
#     class Meta:
#         verbose_name = 'Видео'
#         verbose_name_plural = 'видео'


class Video(models.Model):
    VIDEO_TYPE_CHOICES = (
        ('local', 'Локальное видео'),
        ('url', 'Ссылка на видео'),
    )

    profile = models.ForeignKey('Profile', on_delete=models.CASCADE, related_name='videos')
    video_type = models.CharField(max_length=10, choices=VIDEO_TYPE_CHOICES, default='local', verbose_name='Тип видео')
    video = models.FileField(upload_to='videos/', verbose_name='Видео', blank=True, null=True)
    video_url = models.URLField(blank=True, null=True, verbose_name='Ссылка на видео')
    caption = models.TextField(blank=True, null=True, verbose_name='Подпись')
    likes = models.ManyToManyField(User, related_name='video_likes', blank=True)
    created = models.DateTimeField(auto_now_add=True, verbose_name='Дата')

    def __str__(self):
        return f"{self.profile.nickname} - {self.created}"

    class Meta:
        verbose_name = 'Видео'
        verbose_name_plural = 'видео'



class Message(models.Model):
    sender = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True, related_name='sent_messages')
    recipient = models.ForeignKey(Profile, on_delete=models.SET_NULL, blank=True, null=True,
                                  related_name='received_messages')
    name = models.CharField(max_length=200, blank=True, verbose_name='Имя')
    email = models.EmailField(max_length=200, blank=True, verbose_name='email')
    subject = models.CharField(max_length=200, blank=True, verbose_name='Тема')
    body = models.TextField(verbose_name='Сообщение')
    is_read = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.subject

    class Meta:
        ordering = ['is_read', '-created']
        verbose_name = 'Сообщения'
        verbose_name_plural = 'Сообщение'

sports_app/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Profile, Skill
from django.forms import ModelForm
from .models import Photo, Video, Message


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['nickname', '' 'myself', 'myself_short', 'photo', 'social_youtube',
                  'social_site', 'social_website', 'document', 'work']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field in self.fields.values():
            field.widget.attrs.update({'class': 'input'})


class CustomUserCreationForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=True, label='Имя')
    last_name = forms.CharField(max_length=30, required=True, label='Фамилия')

    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name', 'password1', 'password2']
        labels = {'username': "Логин"}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field in self.fields.values():
            field.widget.attrs.update({'class': 'input'})


class SkillForm(forms.ModelForm):
    class Meta:
        model = Skill
        fields = ['qualification', 'info']
        labels = {'qualification': "Квалификация", 'info': "Опыт"}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field in self.fields.values():
            field.widget.attrs.update({'class': 'input'})


class PhotoForm(forms.ModelForm):
    class Meta:
        model = Photo
        fields = ['image', 'caption']

    def __init__(self, *args, **kwargs):
        super(PhotoForm, self).__init__(*args, **kwargs)

        for field in self.fields.values():
            field.widget.attrs.update({'class': 'input'})


# class VideoForm(forms.ModelForm):
#     class Meta:
#         model = Video
#         fields = ['video', 'caption']
#
#     def __init__(self, *args, **kwargs):
#         super(VideoForm, self).__init__(*args, **kwargs)
#
#         for field in self.fields.values():
#             field.widget.attrs.update({'class': 'input'})


class VideoForm(forms.ModelForm):
    class Meta:
        model = Video
        fields = ['video_type', 'video', 'video_url', 'caption']
        widgets = {
            'video_type': forms.RadioSelect(attrs={'class': 'input'}),
            'video': forms.FileInput(attrs={'class': 'input'}),
            'video_url': forms.URLInput(attrs={'class': 'input'}),
            'caption': forms.Textarea(attrs={'class': 'input'}),
        }

    def __init__(self, *args, **kwargs):
        super(VideoForm, self).__init__(*args, **kwargs)

        for field in self.fields.values():
            field.widget.attrs.update({'class': 'input'})

    def clean(self):
        cleaned_data = super().clean()
        video_type = cleaned_data.get('video_type')
        video = cleaned_data.get('video')
        video_url = cleaned_data.get('video_url')

        if video_type == 'local' and not video:
            self.add_error('video', 'Пожалуйста, загрузите видео файл.')
        elif video_type == 'url' and not video_url:
            self.add_error('video_url', 'Пожалуйста, введите ссылку на видео.')

        return cleaned_data



class MessageForm(ModelForm):
    class Meta:
        model = Message
        fields = ['name', 'email', 'subject', 'body']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field in self.fields.values():
            field.widget.attrs.update({'class': 'input'})

sports_app/users/templates/users/account.html
{% extends 'projects/base.html' %}
{% load static %}
{% block content %}

<main class="settingsPage profile my-md">
    <div class="container">
        <div class="layout">
            <div class="column column--1of3">
                <div class="card text-center">
                    <div class="card__body dev">
                        <a class="tag tag--pill tag--main settings__btn" href="{% url 'edit-account' %}"><i
                                class="im im-edit"></i> Edit</a>
                        <img class="avatar avatar--xl dev__avatar" src="{{ profile.photo.url }}"/>
                        <h2 class="dev__name">{{ profile.name }}</h2>
                        <p class="dev__title">nickname: {{ profile.nickname }}</p>
                        <p class="dev__title">email: {{ profile.email }}</p>
                        <br>
                        <p class="dev__title">{{ profile.myself_short }}</p>
                        <p class="dev__location">{{ profile.work }}</p>
                        <ul class="dev__social">
                            {% if profile.social_site %}
                            <li>
                                <a title="Twitter" href="{{ profile.social_site }}" target="_blank"><i
                                        class="im im-twitter"></i></a>
                            </li>
                            {% endif %}
                            {% if profile.social_youtube %}
                            <li>
                                <a title="Youtube" href="{{ profile.social_youtube }}" target="_blank"><i
                                        class="fa fa-youtube"></i></a>
                            </li>
                            {% endif %}
                            {% if profile.social_website %}
                            <li>
                                <a title="Personal Website" href="{{ profile.social_website }}" target="_blank"><i
                                        class="fa fa-sitemap"></i></a>
                            </li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </div>
            <div class="column column--2of3">
                <div class="devInfo">
                    <h3 class="devInfo__title">Обо мне</h3>
                    <p class="devInfo__about" id="profile-about">
                        {{ profile.myself }}
                    </p>
                </div>
                <p class="devInfo__subtitle"><a href="{{ profile.document.url }}">Диплом</a></p>
                <div class="settings">
                    <h3 class="settings__title">Skills</h3>
                    <a class="tag tag--pill tag--sub settings__btn tag--lg" href="{% url 'create-skill' %}"><i
                            class="im im-plus"></i> Добавить</a>
                </div>

                <table class="settings__table">
                    {% for skill in skills %}
                    <tr>
                        <td class="settings__tableInfo">
                            <h4>{{skill.qualification}}</h4>
                            <p>
                                {{skill.info}}
                            </p>
                        </td>
                        <td class="settings__tableActions">
                            <a class="tag tag--pill tag--main settings__btn" href="{% url 'update-skill' skill.id %}"><i
                                    class="im im-edit"></i> Edit</a>
                            <a class="tag tag--pill tag--main settings__btn" href="{% url 'delete-skill' skill.id %}"><i
                                    class="im im-x-mark-circle-o"></i>
                                Delete</a>
                        </td>
                    </tr>
                    {% endfor %}
                </table>


                <div class="settings">
                    <h3 class="settings__title">Статьи</h3>
                    <a class="tag tag--pill tag--sub settings__btn tag--lg" href="{% url 'create-project' %}"><i
                            class="im im-plus"></i> Добавить</a>
                </div>

                <table class="settings__table">
                    {% for project in profile.project_set.all %}
                    <tr>
                        <td class="settings__thumbnail">
                            <a href="{% url 'project' project.id %}"><img src="{{ project.featured_image.url }}"
                                                                          alt="Project Thumbnail"/></a>
                        </td>
                        <td class="settings__tableInfo">
                            <a href="{% url 'project' project.id %}">{{ project.title }}</a>
                            <p>{{ project.description|safe|truncatewords:40 }}</p>
                        </td>
                        <td class="settings__tableActions">
                            <a class="tag tag--pill tag--main settings__btn"
                               href="{% url 'update-project' project.id %}"><i class="im im-edit"></i>
                                Edit</a>
                            <a class="tag tag--pill tag--main settings__btn"
                               href="{% url 'delete-project' project.id %}"><i
                                    class="im im-x-mark-circle-o"></i>
                                Delete</a>
                        </td>
                    </tr>
                    {% endfor %}
                </table>

                <div class="settings">
                    <h3 class="settings__title">Новости</h3>
                    <a class="tag tag--pill tag--sub settings__btn tag--lg" href="{% url 'upload_photo' %}"><i
                            class="im im-plus"></i> Добавить</a>
                </div>

                <table class="settings__table">
                    {% for photo in profile.photos.all %}
                    <tr>
                        <td class="settings__thumbnail">
                            <a href="{{ photo.image.url }}">
                                <img src="{{ photo.image.url }}" alt="News Thumbnail"/>
                            </a>
                        </td>
                        <td class="settings__tableInfo">
                            <p>{{ photo.caption|truncatewords:40 }}</p>
                        </td>
                        <td class="settings__tableActions">
                            <a class="tag tag--pill tag--main settings__btn" href="{% url 'update-photo' photo.id %}"><i
                                    class="im im-edit"></i>
                                Edit</a>
                            <a class="tag tag--pill tag--main settings__btn" href="{% url 'delete-photo' photo.id %}"><i
                                    class="im im-x-mark-circle-o"></i>
                                Delete</a>
                        </td>
                    </tr>
                    {% endfor %}
                </table>

                <div class="settings">
                    <h3 class="settings__title">Видео</h3>
                    <a class="tag tag--pill tag--sub settings__btn tag--lg" href="{% url 'upload_video' %}"><i
                            class="im im-plus"></i> Добавить</a>
                </div>




<!--                <table class="settings__table">-->
<!--                    {% for video in profile.videos.all %}-->
<!--                    <tr>-->
<!--                        <td class="settings__thumbnail">-->
<!--                            <a href="#">-->
<!--                                <video src="" alt="Video Thumbnail" controls></video>-->
<!--                            </a>-->
<!--                            <br>-->
<!--                        </td>-->
<!--                        <td class="settings__tableInfo">-->
<!--                            <a href="#">{{ video.caption }}</a>-->
<!--                            <p>{{ video.description }}</p>-->
<!--                        </td>-->
<!--                        <td class="settings__tableActions">-->
<!--                            <a class="tag tag&#45;&#45;pill tag&#45;&#45;main settings__btn" href="{% url 'update-video' video.id %}"><i-->
<!--                                    class="im im-edit"></i>-->
<!--                                Edit</a>-->
<!--                            <a class="tag tag&#45;&#45;pill tag&#45;&#45;main settings__btn" href="{% url 'delete-video' video.id %}"><i-->
<!--                                    class="im im-x-mark-circle-o"></i>-->
<!--                                Delete</a>-->
<!--                        </td>-->
<!--                    </tr>-->
<!--                    {% endfor %}-->
<!--                </table>-->



<table class="settings__table">
    {% for video in profile.videos.all %}
    <tr>
        <td class="settings__thumbnail">
            <a href="{% if video.video_type == 'local' and video.video %}{{ video.video.url }}{% elif video.video_type == 'url' %}{{ video.video_url }}{% endif %}">
                {% if video.video_type == 'local' and video.video %}
                <video src="{{ video.video.url }}" alt="Video Thumbnail" controls></video>
                {% elif video.video_type == 'url' %}
                <iframe width="300" height="200" src="{{ video.video_url }}" frameborder="0" allowfullscreen></iframe>
                {% else %}
                <p>Видео не загружено</p>
                {% endif %}
            </a>
            <br>
        </td>
        <td class="settings__tableInfo">
            <a href="{% if video.video_type == 'local' and video.video %}{{ video.video.url }}{% elif video.video_type == 'url' %}{{ video.video_url }}{% endif %}">{{ video.caption }}</a>
            <p>{{ video.description }}</p>
        </td>
        <td class="settings__tableActions">
            <a class="tag tag--pill tag--main settings__btn" href="{% url 'update-video' video.id %}"><i class="im im-edit"></i> Edit</a>
            <a class="tag tag--pill tag--main settings__btn" href="{% url 'delete-video' video.id %}"><i class="im im-x-mark-circle-o"></i> Delete</a>
        </td>
    </tr>
    {% endfor %}
</table>




            </div>
        </div>
    </div>
</main>

{% endblock %}

sports_app/users/templates/users/create_profile.html
{% extends 'projects/base.html' %}
{% load static %}
{% block content %}

<main class="formPage my-xl">
    <div class="content-box">
        <div class="formWrapper">
            <a class="backButton" href="{% url 'projects' %}"><img src="{% static 'images/left.png' %}" alt="left"></a>
            <br>

            <form class="form" method="POST" enctype="multipart/form-data">
                {% csrf_token %}

                <h2>Создать профиль</h2>
                 <p style='color: red; text-align: center'>Создавать профиль могут пользователи, которые имеют документ, подтверждающий их квалификацию.</p>
                {% for field in profile_form %}
                <div class="form__field">
                    <label for="formInput#text">{{ field.label }}: </label>
                    {{ field }}
                </div>
                {% endfor %}

                <input class="btn btn--sub btn--lg  my-md" type="submit" name="submit_project" value="Сохранить"/>
            </form>
        </div>
    </div>
</main>

{% endblock %}

sports_app/users/templates/users/delete-skill.html
{% extends 'projects/base.html' %}
{% load static %}

{% block content %}
<main class="formPage my-xl">
    <div class="content-box">
        <div class="formWrapper">
            <a class="backButton" href="{% url 'account' %}"><img src="{% static 'images/left.png' %}" alt="left"></a>
            <br>

            <h3> Удаление SKILL </h3>
            <p>Вы уверены, что хотите удалить <b>"{{object}}"?</b></p>
            <form class="form" method="post">
                {% csrf_token %}
                <button class="btn btn--sub btn--lg  my-md" type="submit">Да, удалить</button>
                <a class="btn btn--sub btn--lg  my-md" href="{% url 'account' %}">Отменить</a>
            </form>
        </div>
    </div>
</main>
{% endblock %}

sports_app/users/templates/users/index.html
{% extends 'projects/base.html' %}
{% block content %}
<!-- Main Section -->
<main class="home">
    <section class="devlist">
        <div class="container">
            <div class="grid grid--three">
                {% for profile in profiles %}
                <div class="column card">
                    <div class="dev">
                        <a href="{% url 'user_profile' profile.id %}" class="card__body">
                            <div class="dev__profile">
                                <img class="avatar avatar--md" src="{{profile.photo.url }}" alt="image"/>
                                <div class="dev__meta">
                                    <h3>{{profile.name}}</h3>
                                    <h5>{{profile.myself_short|slice:'50'}}</h5>
                                </div>
                            </div>
                            <p class="dev__info">
                                {{profile.myself|slice:'150'}}
                            </p>
                            <div class="dev__skills">
                                {% for skill in profile.skill_set.all %}
                                <span class="tag tag--pill tag--main">
                    <small>{{ skill }}</small>
                  </span>
                                {% endfor %}
                            </div>
                        </a>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </section>

    {% include 'projects/pagination.html' with queryset=profiles %}
</main>

{% endblock %}

sports_app/users/templates/users/login_register.html
{% extends 'projects/base.html' %}
{% load static %}
{% block content %}


{% if page == 'register' %}

 <div class="auth">
      <div class="card">
        <div class="auth__header text-center">
          <a href="/">
            <img src="{% static 'images/logo.jpg' %}" alt="icon" style="width: 15%;" />
          </a>
          <h3>Регистрация</h3>
          <p>Создайте новую учетную запись </p>
        </div>

        <form action="{% url 'register' %}" class="form auth__form"  method="post">
          {% csrf_token %}

          {% for field in form %}
          <!-- Input:Text -->
          <div class="form__field">
            <label for="formInput#text"> {{ field.label }}</label>
            {{ field }}
            {% for error in field.errors %}
            <p style="color:red">{{error}}</p>
            {% endfor %}
          </div>
          {% endfor %}
          <div class="auth__actions">
            <input class="btn btn--sub btn--lg" type="submit" value="Зарегистрироваться" />
          </div>
        </form>
        <div class="auth__alternative">
          <p>У вас уже есть учетная запись?</p>
          <a href="{% url 'login' %}" style="font-size: 1.8rem; color: var(--color-main); ">Авторизация</a>
        </div>
      </div>
    </div>

{% else %}

 <div class="auth">
      <div class="card">
        <div class="auth__header text-center">
          <a href="/">
            <img src="{% static 'images/logo.jpg' %}" alt="icon" style="width: 15%;" />
          </a>
          <h3>Авторизация</h3>
          <p>Добро пожаловать!</p>
        </div>

        <form action="{% url 'login' %}" class="form auth__form" method="post" >
            {% csrf_token %}
          <!-- Input:Email -->
          <div class="form__field">
            <label for="formInput#text">Username: </label>
            <input
              class="input input--text"
              id="formInput#text"
              type="text"
              name="username"
              placeholder="Enter your username..."
            />
          </div>

          <!-- Input:Password -->
          <div class="form__field">
            <label for="formInput#passowrd">Password: </label>
            <input
              class="input input--password"
              id="formInput#passowrd"
              type="password"
              name="password"
              placeholder="••••••••"
            />
          </div>
          <div class="auth__actions">
            <input class="btn btn--sub btn--lg" type="submit" value="Войти"/>
<!--            <a href="{% url 'password_reset' %}" style="font-size: 1.8rem; color: var(&#45;&#45;color-main); ">Забыли пароль?</a>-->
          </div>
        </form>
        <div class="auth__alternative">
          <p>У вас еще нет учетной записи?</p>
          <a href="{% url 'register' %}" style="font-size: 1.8rem; color: var(--color-main);">Зарегистрироваться</a>
        </div>
      </div>
    </div>

{% endif %}



{% endblock %}

sports_app/users/templates/users/message.html
{% extends 'projects/base.html' %}
{% load static %}
{% block content %}

  <!-- Main Section -->
  <main class="messagePage my-xl">
    <div class="content-box">
      <div class="message">
        <a class="backButton" href="{% url 'inbox' %}"><img src="{% static 'images/left.png' %}" alt="left"></a>
        <h2 class="message__subject">{{ message.subject }}</h2>
          <a href="#" class="message__author">{{ message.name }}</a>
          <p class="message__date">{{ message.created }}</p>
          <div class="message__body">
            {{message.body|linebreaksbr }}
          </div>
      </div>
    </div>
  </main>

{% endblock %}